name: Update Tags File

on:
  push:
    tags:
      - '*' # Triggers on any new tag being pushed

jobs:
  generate-tags-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get list of tags
        run: |
          git tag --sort=-creatordate > tags.txt
          echo "tags.txt file updated with the latest tags"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tags.txt
          git commit -m "Update tags.txt with new tags"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
